import { Profile } from '@/features/profiles/types';

export const mockProfiles: Profile[] = [
  {
    id: '1',
    slug: 'teknoloji-gurusu',
    title: 'Yapay Zeka ve Geleceğin Teknolojileri',
    name: 'Ahmet Yılmaz',
    topic: 'bilim',
    image_url: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=600&fit=crop',
    youtube_nick: 'ahmetyilmaz',
    twitter_nick: 'ahmetyilmaz',
    instagram_nick: 'ahmetyilmaz_tech',
    youtube_url: 'https://youtube.com/@ahmetyilmaz',
    twitter_url: 'https://twitter.com/ahmetyilmaz',
    instagram_url: 'https://instagram.com/ahmetyilmaz_tech',
    description: 'Yapay zeka, makine öğrenmesi ve gelecek teknolojileri hakkında içerikler üretiyorum. 10+ yıllık yazılım geliştirme deneyimi.',
    status: 'featured',
    view_count: 15420,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z'
  },
  {
    id: '2',
    slug: 'bilim-kanali',
    title: 'Evrenin Sırları ve Kuantum Fiziği',
    name: 'Dr. Zeynep Kaya',
    topic: 'bilim',
    image_url: 'https://images.unsplash.com/photo-1636690619602-3a9d9b5f1e15?w=800&h=600&fit=crop',
    youtube_nick: 'zeynepkaya',
    twitter_nick: 'drzkaya',
    youtube_url: 'https://youtube.com/@zeynepkaya',
    twitter_url: 'https://twitter.com/drzkaya',
    description: 'Fizik profesörü. Kuantum mekaniği, astrofizik ve evrenin gizemlerini anlatıyorum.',
    status: 'featured',
    view_count: 12350,
    created_at: '2024-01-14T10:00:00Z',
    updated_at: '2024-01-14T10:00:00Z'
  },
  {
    id: '3',
    slug: 'tarih-hikayeleri',
    title: 'Osmanlı Tarihi ve Kültürü',
    name: 'Mehmet Demir',
    topic: 'tarih',
    image_url: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800&h=600&fit=crop',
    youtube_nick: 'mehmetdemir',
    instagram_nick: 'tarihci_mehmet',
    tiktok_nick: 'mehmetdemir',
    youtube_url: 'https://youtube.com/@mehmetdemir',
    instagram_url: 'https://instagram.com/tarihci_mehmet',
    tiktok_url: 'https://tiktok.com/@mehmetdemir',
    description: 'Tarih öğretmeni. Osmanlı tarihi, İslam medeniyeti ve kültür tarihi üzerine içerikler.',
    status: 'verified',
    view_count: 8720,
    created_at: '2024-01-13T10:00:00Z',
    updated_at: '2024-01-13T10:00:00Z'
  },
  {
    id: '4',
    slug: 'saglik-yasam',
    title: 'Sağlıklı Yaşam ve Beslenme',
    name: 'Ayşe Yıldız',
    topic: 'bilim',
    image_url: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&h=600&fit=crop',
    youtube_nick: 'ayseyildiz',
    instagram_nick: 'dyt_ayse',
    youtube_url: 'https://youtube.com/@ayseyildiz',
    instagram_url: 'https://instagram.com/dyt_ayse',
    description: 'Diyetisyen. Sağlıklı beslenme, diyet ve yaşam tarzı koçluğu yapıyorum.',
    status: 'verified',
    view_count: 6890,
    created_at: '2024-01-12T10:00:00Z',
    updated_at: '2024-01-12T10:00:00Z'
  },
  {
    id: '5',
    slug: 'programlama-dersleri',
    title: 'Python ve Web Geliştirme',
    name: 'Can Özkan',
    topic: 'bilim',
    image_url: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=600&fit=crop',
    youtube_nick: 'canozkan',
    twitter_nick: 'canozkan_dev',
    youtube_url: 'https://youtube.com/@canozkan',
    twitter_url: 'https://twitter.com/canozkan_dev',
    description: 'Yazılım mühendisi. Python, JavaScript ve web geliştirme eğitimleri.',
    status: 'standard',
    view_count: 4520,
    created_at: '2024-01-11T10:00:00Z',
    updated_at: '2024-01-11T10:00:00Z'
  },
  {
    id: '6',
    slug: 'psikoloji-soylesi',
    title: 'Kişisel Gelişim ve Psikoloji',
    name: 'Selin Aydın',
    topic: 'din-felsefe',
    image_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&h=600&fit=crop',
    youtube_nick: 'selinaydin',
    instagram_nick: 'psikolog_selin',
    tiktok_nick: 'selinaydin',
    youtube_url: 'https://youtube.com/@selinaydin',
    instagram_url: 'https://instagram.com/psikolog_selin',
    tiktok_url: 'https://tiktok.com/@selinaydin',
    description: 'Klinik psikolog. Kişisel gelişim, mental sağlık ve psikoloji üzerine içerikler.',
    status: 'featured',
    view_count: 11250,
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-01-10T10:00:00Z'
  },
  {
    id: '7',
    slug: 'spor-fitness',
    title: 'Fitness ve Vücut Geliştirme',
    name: 'Emre Şahin',
    topic: 'gundem',
    image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=600&fit=crop',
    youtube_nick: 'emresahin',
    instagram_nick: 'coach_emre',
    youtube_url: 'https://youtube.com/@emresahin',
    instagram_url: 'https://instagram.com/coach_emre',
    description: 'Fitness antrenörü. Vücut geliştirme, antrenman programları ve spor beslenmesi.',
    status: 'verified',
    view_count: 7630,
    created_at: '2024-01-09T10:00:00Z',
    updated_at: '2024-01-09T10:00:00Z'
  },
  {
    id: '8',
    slug: 'ekonomi-finans',
    title: 'Kripto Para ve Yatırım',
    name: 'Burak Yılmaz',
    topic: 'gundem',
    image_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=600&fit=crop',
    youtube_nick: 'burakyilmaz',
    twitter_nick: 'burakyilmaz_tr',
    youtube_url: 'https://youtube.com/@burakyilmaz',
    twitter_url: 'https://twitter.com/burakyilmaz_tr',
    description: 'Finans analisti. Kripto para, borsa ve yatırım stratejileri hakkında analizler.',
    status: 'standard',
    view_count: 5420,
    created_at: '2024-01-08T10:00:00Z',
    updated_at: '2024-01-08T10:00:00Z'
  }
];
